[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Blake Winton <bwinton@latte.ca>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
clap = "2.32.0"
chrono = "0.4.6"
combine = "3.6.6"
custom_error = "1.3.0"
derive_more = "0.13.0"
itertools = "0.8.0"
lazy_static = "1.2.0"
maplit = "1.0.1"
permutohedron = "0.2.4"
rayon = "1.0.3"
regex = "1.1.0"
reqwest = "0.9.8"
rust-crypto = "0.2.36"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.34"

[dependencies.nom]
version = "4.1.1"
features = ["verbose-errors"]

[lib]
name = "aoc"

[[bin]]
name = "stats"
path = "src/stats.rs"

[[bin]]
name = "2015"
path = "src/2015/main.rs"

[[bin]]
name = "2016"
path = "src/2016/main.rs"

[[bin]]
name = "2017"
path = "src/2017/main.rs"

[[bin]]
name = "2018"
path = "src/2018/main.rs"

