[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Blake Winton <bwinton@latte.ca>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
clap = "2.33.0"
chrono = "0.4.10"
color-backtrace = "0.3.0"
combine = "3.8.1"
crossterm = "0.14.1"
custom_error = "1.7.1"
derive_more = "0.99.2"
glue = "0.8.3"
itertools = "0.8.2"
lazy_static = "1.4.0"
maplit = "1.0.2"
mod_exp = "1.0.1"
num-integer = "0.1.41"
num-rational = "0.2.2"
permutohedron = "0.2.4"
rayon = "1.2.1"
regex = "1.3.1"
reqwest = "0.9.22"
rust-crypto = "0.2.36"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"

[lib]
name = "aoc"

[[bin]]
name = "stats"
path = "src/stats.rs"

[[bin]]
name = "2015"
path = "src/2015/main.rs"

[[bin]]
name = "2016"
path = "src/2016/main.rs"

[[bin]]
name = "2017"
path = "src/2017/main.rs"

[[bin]]
name = "2018"
path = "src/2018/main.rs"

[[bin]]
name = "2019"
path = "src/2019/main.rs"
