[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Blake Winton <bwinton@latte.ca>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
clap = "2.33.0"
chrono = "0.4.6"
combine = "3.8.1"
crossterm = "0.9.1"
custom_error = "1.6.0"
derive_more = "0.14.0"
itertools = "0.8.0"
lazy_static = "1.3.0"
maplit = "1.0.1"
permutohedron = "0.2.4"
rayon = "1.0.3"
regex = "1.1.5"
reqwest = "0.9.14"
rust-crypto = "0.2.36"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"

[dependencies.nom]
version = "4.2.3"
features = ["verbose-errors"]

[lib]
name = "aoc"

[[bin]]
name = "stats"
path = "src/stats.rs"

[[bin]]
name = "2015"
path = "src/2015/main.rs"

[[bin]]
name = "2016"
path = "src/2016/main.rs"

[[bin]]
name = "2017"
path = "src/2017/main.rs"

[[bin]]
name = "2018"
path = "src/2018/main.rs"

